import type { Agent } from "@/types/agent"
import type { Match } from "@/types/match"

// Real tournament data for the first two days of the Round of 64
const tournamentData: Match[] = [
  // Thursday, March 20, 2025
  {
    id: "match-1-1",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Thursday, March 20, 2025",
    time: "10:15 AM MST",
    location: "Rupp Arena, Lexington, KY",
    teamA: {
      id: "creighton",
      name: "Creighton",
      seed: 9,
      score: 0,
      record: "24-9",
    },
    teamB: {
      id: "louisville",
      name: "Louisville",
      seed: 8,
      score: 0,
      record: "23-10",
    },
    winner: null,
    predictions: {
      claude: "louisville",
      gpt4o: "louisville",
      perplexity: "louisville",
      deepseek: "creighton",
      grok: "creighton",
      gemini: "creighton",
    },
    teams: [
      {
        id: "creighton",
        name: "Creighton",
        seed: 9,
        score: 0,
        record: "24-9",
      },
      {
        id: "louisville",
        name: "Louisville",
        seed: 8,
        score: 0,
        record: "23-10",
      },
    ],
    pointSpread: 1,
    pointSpreadSource: "CBSSports.com, Anonymous Eagle",
  },
  {
    id: "match-1-2",
    round: 1,
    roundName: "First Round",
    region: "Midwest",
    date: "Thursday, March 20, 2025",
    time: "10:40 AM MST",
    location: "Amica Mutual Pavilion, Providence, RI",
    teamA: {
      id: "high-point",
      name: "High Point",
      seed: 13,
      score: 0,
      record: "24-11",
    },
    teamB: {
      id: "purdue",
      name: "Purdue",
      seed: 4,
      score: 0,
      record: "29-7",
    },
    winner: null,
    predictions: {
      claude: "purdue",
      gpt4o: "purdue",
      perplexity: "purdue",
      deepseek: "purdue",
      grok: "purdue",
      gemini: "purdue",
    },
    teams: [
      {
        id: "high-point",
        name: "High Point",
        seed: 13,
        score: 0,
        record: "24-11",
      },
      {
        id: "purdue",
        name: "Purdue",
        seed: 4,
        score: 0,
        record: "29-7",
      },
    ],
    pointSpread: 6,
    pointSpreadSource: "NCAA.com, CBSSports.com",
  },
  {
    id: "match-1-3",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Thursday, March 20, 2025",
    time: "11:30 AM MST",
    location: "Intrust Bank Arena, Wichita, KS",
    teamA: {
      id: "montana",
      name: "Montana",
      seed: 14,
      score: 0,
      record: "23-11",
    },
    teamB: {
      id: "wisconsin",
      name: "Wisconsin",
      seed: 3,
      score: 0,
      record: "26-8",
    },
    winner: null,
    predictions: {
      claude: "wisconsin",
      gpt4o: "wisconsin",
      perplexity: "wisconsin",
      deepseek: "wisconsin",
      grok: "wisconsin",
      gemini: "wisconsin",
    },
    teams: [
      {
        id: "montana",
        name: "Montana",
        seed: 14,
        score: 0,
        record: "23-11",
      },
      {
        id: "wisconsin",
        name: "Wisconsin",
        seed: 3,
        score: 0,
        record: "26-8",
      },
    ],
    pointSpread: 1,
    pointSpreadSource: "ESPN.com, Wikipedia",
  },
  {
    id: "match-1-4",
    round: 1,
    roundName: "First Round",
    region: "Midwest",
    date: "Thursday, March 20, 2025",
    time: "12:00 PM MST",
    location: "Ball Arena, Denver, CO",
    teamA: {
      id: "siu-edwardsville",
      name: "SIU Edwardsville",
      seed: 16,
      score: 0,
      record: "19-15",
    },
    teamB: {
      id: "houston",
      name: "Houston",
      seed: 1,
      score: 0,
      record: "31-4",
    },
    winner: null,
    predictions: {
      claude: "houston",
      gpt4o: "houston",
      perplexity: "houston",
      deepseek: "houston",
      grok: "houston",
      gemini: "houston",
    },
    teams: [
      {
        id: "siu-edwardsville",
        name: "SIU Edwardsville",
        seed: 16,
        score: 0,
        record: "19-15",
      },
      {
        id: "houston",
        name: "Houston",
        seed: 1,
        score: 0,
        record: "31-4",
      },
    ],
    pointSpread: 7,
    pointSpreadSource: "ESPN.com, CBSSports.com, NBC Sports",
  },
  {
    id: "match-1-5",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Thursday, March 20, 2025",
    time: "12:50 PM MST",
    location: "Rupp Arena, Lexington, KY",
    teamA: {
      id: "alabama-state",
      name: "Alabama State",
      seed: 16,
      score: 0,
      record: "20-14",
    },
    teamB: {
      id: "auburn",
      name: "Auburn",
      seed: 1,
      score: 0,
      record: "27-7",
    },
    winner: null,
    predictions: {
      claude: "auburn",
      gpt4o: "auburn",
      perplexity: "auburn",
      deepseek: "auburn",
      grok: "auburn",
      gemini: "auburn",
    },
    teams: [
      {
        id: "alabama-state",
        name: "Alabama State",
        seed: 16,
        score: 0,
        record: "20-14",
      },
      {
        id: "auburn",
        name: "Auburn",
        seed: 1,
        score: 0,
        record: "27-7",
      },
    ],
    pointSpread: 11,
    pointSpreadSource: "NCAA.com, SBNation.com, CBSSports.com",
  },
  {
    id: "match-1-6",
    round: 1,
    roundName: "First Round",
    region: "Midwest",
    date: "Thursday, March 20, 2025",
    time: "1:15 PM MST",
    location: "Amica Mutual Pavilion, Providence, RI",
    teamA: {
      id: "mcneese",
      name: "McNeese",
      seed: 12,
      score: 0,
      record: "25-9",
    },
    teamB: {
      id: "clemson",
      name: "Clemson",
      seed: 5,
      score: 0,
      record: "24-11",
    },
    winner: null,
    predictions: {
      claude: "clemson",
      gpt4o: "clemson",
      perplexity: "clemson",
      deepseek: "clemson",
      grok: "mcneese",
      gemini: "mcneese",
    },
    teams: [
      {
        id: "mcneese",
        name: "McNeese",
        seed: 12,
        score: 0,
        record: "25-9",
      },
      {
        id: "clemson",
        name: "Clemson",
        seed: 5,
        score: 0,
        record: "24-11",
      },
    ],
    pointSpread: 4,
    pointSpreadSource: "NCAA.com, CBSSports.com, Anonymous Eagle",
  },
  {
    id: "match-1-7",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Thursday, March 20, 2025",
    time: "2:05 PM MST",
    location: "Intrust Bank Arena, Wichita, KS",
    teamA: {
      id: "vcu",
      name: "VCU",
      seed: 11,
      score: 0,
      record: "23-13",
    },
    teamB: {
      id: "byu",
      name: "BYU",
      seed: 6,
      score: 0,
      record: "23-10",
    },
    winner: null,
    predictions: {
      claude: "vcu",
      gpt4o: "vcu",
      perplexity: "byu",
      deepseek: "vcu",
      grok: "byu",
      gemini: "byu",
    },
    teams: [
      {
        id: "vcu",
        name: "VCU",
        seed: 11,
        score: 0,
        record: "23-13",
      },
      {
        id: "byu",
        name: "BYU",
        seed: 6,
        score: 0,
        record: "23-10",
      },
    ],
    pointSpread: 3,
    pointSpreadSource: "NCAA.com, CBSSports.com, Anonymous Eagle",
  },
  {
    id: "match-1-8",
    round: 1,
    roundName: "First Round",
    region: "Midwest",
    date: "Thursday, March 20, 2025",
    time: "2:35 PM MST",
    location: "Ball Arena, Denver, CO",
    teamA: {
      id: "georgia",
      name: "Georgia",
      seed: 9,
      score: 0,
      record: "20-16",
    },
    teamB: {
      id: "gonzaga",
      name: "Gonzaga",
      seed: 8,
      score: 0,
      record: "25-7",
    },
    winner: null,
    predictions: {
      claude: "gonzaga",
      gpt4o: "gonzaga",
      perplexity: "gonzaga",
      deepseek: "gonzaga",
      grok: "georgia",
      gemini: "gonzaga",
    },
    teams: [
      {
        id: "georgia",
        name: "Georgia",
        seed: 9,
        score: 0,
        record: "20-16",
      },
      {
        id: "gonzaga",
        name: "Gonzaga",
        seed: 8,
        score: 0,
        record: "25-7",
      },
    ],
    pointSpread: 2,
    pointSpreadSource: "NCAA.com, CBSSports.com",
  },
  {
    id: "match-1-9",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Thursday, March 20, 2025",
    time: "4:50 PM MST",
    location: "Intrust Bank Arena, Wichita, KS",
    teamA: {
      id: "wofford",
      name: "Wofford",
      seed: 15,
      score: 0,
      record: "21-12",
    },
    teamB: {
      id: "tennessee",
      name: "Tennessee",
      seed: 2,
      score: 0,
      record: "26-8",
    },
    winner: null,
    predictions: {
      claude: "tennessee",
      gpt4o: "tennessee",
      perplexity: "tennessee",
      deepseek: "tennessee",
      grok: "tennessee",
      gemini: "tennessee",
    },
    teams: [
      {
        id: "wofford",
        name: "Wofford",
        seed: 15,
        score: 0,
        record: "21-12",
      },
      {
        id: "tennessee",
        name: "Tennessee",
        seed: 2,
        score: 0,
        record: "26-8",
      },
    ],
    pointSpread: 2,
    pointSpreadSource: "NCAA.com, ESPN.com, Wikipedia",
  },
  {
    id: "match-1-10",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Thursday, March 20, 2025",
    time: "5:10 PM MST",
    location: "Rupp Arena, Lexington, KY",
    teamA: {
      id: "arkansas",
      name: "Arkansas",
      seed: 10,
      score: 0,
      record: "22-13",
    },
    teamB: {
      id: "kansas",
      name: "Kansas",
      seed: 7,
      score: 0,
      record: "23-10",
    },
    winner: null,
    predictions: {
      claude: "kansas",
      gpt4o: "kansas",
      perplexity: "kansas",
      deepseek: "kansas",
      grok: "kansas",
      gemini: "kansas",
    },
    teams: [
      {
        id: "arkansas",
        name: "Arkansas",
        seed: 10,
        score: 0,
        record: "22-13",
      },
      {
        id: "kansas",
        name: "Kansas",
        seed: 7,
        score: 0,
        record: "23-10",
      },
    ],
    pointSpread: 2,
    pointSpreadSource: "NCAA.com, CBSSports.com, ESPN.com, Wikipedia",
  },
  {
    id: "match-1-11",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Thursday, March 20, 2025",
    time: "5:25 PM MST",
    location: "Ball Arena, Denver, CO",
    teamA: {
      id: "yale",
      name: "Yale",
      seed: 13,
      score: 0,
      record: "22-9",
    },
    teamB: {
      id: "texas-am",
      name: "Texas A&M",
      seed: 4,
      score: 0,
      record: "24-9",
    },
    winner: null,
    predictions: {
      claude: "texas-am",
      gpt4o: "yale",
      perplexity: "texas-am",
      deepseek: "texas-am",
      grok: "yale",
      gemini: "yale",
    },
    teams: [
      {
        id: "yale",
        name: "Yale",
        seed: 13,
        score: 0,
        record: "22-9",
      },
      {
        id: "texas-am",
        name: "Texas A&M",
        seed: 4,
        score: 0,
        record: "24-9",
      },
    ],
    pointSpread: 2,
    pointSpreadSource: "CBSSports.com, NCAA.com",
  },
  {
    id: "match-1-12",
    round: 1,
    roundName: "First Round",
    region: "Midwest",
    date: "Thursday, March 20, 2025",
    time: "5:35 PM MST",
    location: "Amica Mutual Pavilion, Providence, RI",
    teamA: {
      id: "drake",
      name: "Drake",
      seed: 11,
      score: 0,
      record: "28-6",
    },
    teamB: {
      id: "missouri",
      name: "Missouri",
      seed: 6,
      score: 0,
      record: "24-10",
    },
    winner: null,
    predictions: {
      claude: "drake",
      gpt4o: "drake",
      perplexity: "drake",
      deepseek: "missouri",
      grok: "missouri",
      gemini: "missouri",
    },
    teams: [
      {
        id: "drake",
        name: "Drake",
        seed: 11,
        score: 0,
        record: "28-6",
      },
      {
        id: "missouri",
        name: "Missouri",
        seed: 6,
        score: 0,
        record: "24-10",
      },
    ],
    pointSpread: 2,
    pointSpreadSource: "NCAA.com, ESPN.com, Wikipedia",
  },
  {
    id: "match-1-13",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Thursday, March 20, 2025",
    time: "7:25 PM MST",
    location: "Intrust Bank Arena, Wichita, KS",
    teamA: {
      id: "utah-state",
      name: "Utah State",
      seed: 10,
      score: 0,
      record: "26-6",
    },
    teamB: {
      id: "ucla",
      name: "UCLA",
      seed: 7,
      score: 0,
      record: "23-10",
    },
    winner: null,
    predictions: {
      claude: "ucla",
      gpt4o: "ucla",
      perplexity: "ucla",
      deepseek: "ucla",
      grok: "utah-state",
      gemini: "utah-state",
    },
    teams: [
      {
        id: "utah-state",
        name: "Utah State",
        seed: 10,
        score: 0,
        record: "26-6",
      },
      {
        id: "ucla",
        name: "UCLA",
        seed: 7,
        score: 0,
        record: "23-10",
      },
    ],
    pointSpread: 5,
    pointSpreadSource: "SBNation.com, CBSSports.com, NCAA.com",
  },
  {
    id: "match-1-14",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Thursday, March 20, 2025",
    time: "7:45 PM MST",
    location: "Rupp Arena, Lexington, KY",
    teamA: {
      id: "omaha",
      name: "Omaha",
      seed: 15,
      score: 0,
      record: "21-14",
    },
    teamB: {
      id: "st-johns",
      name: "St. John's",
      seed: 2,
      score: 0,
      record: "27-6",
    },
    winner: null,
    predictions: {
      claude: "st-johns",
      gpt4o: "st-johns",
      perplexity: "st-johns",
      deepseek: "omaha",
      grok: "st-johns",
      gemini: "st-johns",
    },
    teams: [
      {
        id: "omaha",
        name: "Omaha",
        seed: 15,
        score: 0,
        record: "21-14",
      },
      {
        id: "st-johns",
        name: "St. John's",
        seed: 2,
        score: 0,
        record: "27-6",
      },
    ],
  },
  {
    id: "match-1-15",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Thursday, March 20, 2025",
    time: "8:00 PM MST",
    location: "Ball Arena, Denver, CO",
    teamA: {
      id: "uc-san-diego",
      name: "UC San Diego",
      seed: 12,
      score: 0,
      record: "23-11",
    },
    teamB: {
      id: "michigan",
      name: "Michigan",
      seed: 5,
      score: 0,
      record: "24-10",
    },
    winner: null,
    predictions: {
      claude: "michigan",
      gpt4o: "michigan",
      perplexity: "uc-san-diego",
      deepseek: "uc-san-diego",
      grok: "michigan",
      gemini: "uc-san-diego",
    },
    teams: [
      {
        id: "uc-san-diego",
        name: "UC San Diego",
        seed: 12,
        score: 0,
        record: "23-11",
      },
      {
        id: "michigan",
        name: "Michigan",
        seed: 5,
        score: 0,
        record: "24-10",
      },
    ],
  },
  {
    id: "match-1-16",
    round: 1,
    roundName: "First Round",
    region: "Midwest",
    date: "Thursday, March 20, 2025",
    time: "8:10 PM MST",
    location: "Amica Mutual Pavilion, Providence, RI",
    teamA: {
      id: "unc-wilmington",
      name: "UNC Wilmington",
      seed: 14,
      score: 0,
      record: "24-10",
    },
    teamB: {
      id: "texas-tech",
      name: "Texas Tech",
      seed: 3,
      score: 0,
      record: "25-9",
    },
    winner: null,
    predictions: {
      claude: "texas-tech",
      gpt4o: "texas-tech",
      perplexity: "texas-tech",
      deepseek: "texas-tech",
      grok: "texas-tech",
      gemini: "texas-tech",
    },
    teams: [
      {
        id: "unc-wilmington",
        name: "UNC Wilmington",
        seed: 14,
        score: 0,
        record: "24-10",
      },
      {
        id: "texas-tech",
        name: "Texas Tech",
        seed: 3,
        score: 0,
        record: "25-9",
      },
    ],
    pointSpread: 4,
    pointSpreadSource: "Anonymous Eagle, NCAA.com",
  },
  // Friday, March 21, 2025
  {
    id: "match-1-17",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Friday, March 21, 2025",
    time: "10:15 AM MST",
    location: "Rocket Arena, Cleveland, OH",
    teamA: {
      id: "baylor",
      name: "Baylor",
      seed: 9,
      score: 0,
      record: "23-10",
    },
    teamB: {
      id: "mississippi-state",
      name: "Mississippi State",
      seed: 8,
      score: 0,
      record: "21-13",
    },
    winner: null,
    predictions: {
      claude: "mississippi-state",
      gpt4o: "mississippi-state",
      perplexity: "baylor",
      deepseek: "baylor",
      grok: "mississippi-state",
      gemini: "mississippi-state",
    },
    teams: [
      {
        id: "baylor",
        name: "Baylor",
        seed: 9,
        score: 0,
        record: "23-10",
      },
      {
        id: "mississippi-state",
        name: "Mississippi State",
        seed: 8,
        score: 0,
        record: "21-13",
      },
    ],
    pointSpread: 1,
    pointSpreadSource: "Wikipedia, ESPN.com",
  },
  {
    id: "match-1-18",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Friday, March 21, 2025",
    time: "10:40 AM MST",
    location: "Fiserv Forum, Milwaukee, WI",
    teamA: {
      id: "robert-morris",
      name: "Robert Morris",
      seed: 15,
      score: 0,
      record: "20-14",
    },
    teamB: {
      id: "alabama",
      name: "Alabama",
      seed: 2,
      score: 0,
      record: "27-7",
    },
    winner: null,
    predictions: {
      claude: "alabama",
      gpt4o: "alabama",
      perplexity: "alabama",
      deepseek: "alabama",
      grok: "alabama",
      gemini: "alabama",
    },
    teams: [
      {
        id: "robert-morris",
        name: "Robert Morris",
        seed: 15,
        score: 0,
        record: "20-14",
      },
      {
        id: "alabama",
        name: "Alabama",
        seed: 2,
        score: 0,
        record: "27-7",
      },
    ],
    pointSpread: 3,
    pointSpreadSource: "NCAA.com, CBSSports.com",
  },
  {
    id: "match-1-19",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Friday, March 21, 2025",
    time: "11:30 AM MST",
    location: "Lenovo Center, Raleigh, NC",
    teamA: {
      id: "lipscomb",
      name: "Lipscomb",
      seed: 14,
      score: 0,
      record: "22-12",
    },
    teamB: {
      id: "iowa-state",
      name: "Iowa State",
      seed: 3,
      score: 0,
      record: "27-7",
    },
    winner: null,
    predictions: {
      claude: "iowa-state",
      gpt4o: "iowa-state",
      perplexity: "iowa-state",
      deepseek: "iowa-state",
      grok: "iowa-state",
      gemini: "iowa-state",
    },
    teams: [
      {
        id: "lipscomb",
        name: "Lipscomb",
        seed: 14,
        score: 0,
        record: "22-12",
      },
      {
        id: "iowa-state",
        name: "Iowa State",
        seed: 3,
        score: 0,
        record: "27-7",
      },
    ],
    pointSpread: 1,
    pointSpreadSource: "CBSSports.com, NCAA.com, Wikipedia, ESPN.com",
  },
  {
    id: "match-1-20",
    round: 1,
    roundName: "First Round",
    region: "West",
    date: "Friday, March 21, 2025",
    time: "12:00 PM MST",
    location: "Climate Pledge Arena, Seattle, WA",
    teamA: {
      id: "colorado-state",
      name: "Colorado State",
      seed: 12,
      score: 0,
      record: "24-10",
    },
    teamB: {
      id: "memphis",
      name: "Memphis",
      seed: 5,
      score: 0,
      record: "26-8",
    },
    winner: null,
    predictions: {
      claude: "colorado-state",
      gpt4o: "memphis",
      perplexity: "memphis",
      deepseek: "colorado-state",
      grok: "colorado-state",
      gemini: "colorado-state",
    },
    teams: [
      {
        id: "colorado-state",
        name: "Colorado State",
        seed: 12,
        score: 0,
        record: "24-10",
      },
      {
        id: "memphis",
        name: "Memphis",
        seed: 5,
        score: 0,
        record: "26-8",
      },
    ],
    pointSpread: 1,
    pointSpreadSource: "ESPN.com, Wikipedia",
  },
  {
    id: "match-1-21",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Friday, March 21, 2025",
    time: "12:50 PM MST",
    location: "Rocket Arena, Cleveland, OH",
    teamA: {
      id: "mount-st-marys",
      name: "Mount St. Mary's/American",
      seed: 16,
      score: 0,
      record: "19-15",
    },
    teamB: {
      id: "duke",
      name: "Duke",
      seed: 1,
      score: 0,
      record: "29-6",
    },
    winner: null,
    predictions: {
      claude: "duke",
      gpt4o: "duke",
      perplexity: "duke",
      deepseek: "duke",
      grok: "duke",
      gemini: "duke",
    },
    teams: [
      {
        id: "mount-st-marys",
        name: "Mount St. Mary's/American",
        seed: 16,
        score: 0,
        record: "19-15",
      },
      {
        id: "duke",
        name: "Duke",
        seed: 1,
        score: 0,
        record: "29-6",
      },
    ],
    pointSpread: 5,
    pointSpreadSource: "Big Rapids Pioneer, CBSSports.com, NCAA.com",
  },
  {
    id: "match-1-22",
    round: 1,
    roundName: "First Round",
    region: "West",
    date: "Friday, March 21, 2025",
    time: "1:15 PM MST",
    location: "Fiserv Forum, Milwaukee, WI",
    teamA: {
      id: "vanderbilt",
      name: "Vanderbilt",
      seed: 10,
      score: 0,
      record: "21-14",
    },
    teamB: {
      id: "saint-marys",
      name: "Saint Mary's",
      seed: 7,
      score: 0,
      record: "25-8",
    },
    winner: null,
    predictions: {
      claude: "saint-marys",
      gpt4o: "saint-marys",
      perplexity: "saint-marys",
      deepseek: "vanderbilt",
      grok: "saint-marys",
      gemini: "saint-marys",
    },
    teams: [
      {
        id: "vanderbilt",
        name: "Vanderbilt",
        seed: 10,
        score: 0,
        record: "21-14",
      },
      {
        id: "saint-marys",
        name: "Saint Mary's",
        seed: 7,
        score: 0,
        record: "25-8",
      },
    ],
    pointSpread: 3,
    pointSpreadSource: "NCAA.com, CBSSports.com",
  },
  {
    id: "match-1-23",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Friday, March 21, 2025",
    time: "2:05 PM MST",
    location: "Lenovo Center, Raleigh, NC",
    teamA: {
      id: "north-carolina",
      name: "North Carolina",
      seed: 11,
      score: 0,
      record: "20-14",
    },
    teamB: {
      id: "ole-miss",
      name: "Ole Miss",
      seed: 6,
      score: 0,
      record: "24-9",
    },
    winner: null,
    predictions: {
      claude: "north-carolina",
      gpt4o: "north-carolina",
      perplexity: "ole-miss",
      deepseek: "north-carolina",
      grok: "north-carolina",
      gemini: "north-carolina",
    },
    teams: [
      {
        id: "north-carolina",
        name: "North Carolina",
        seed: 11,
        score: 0,
        record: "20-14",
      },
      {
        id: "ole-miss",
        name: "Ole Miss",
        seed: 6,
        score: 0,
        record: "24-9",
      },
    ],
    pointSpread: 4,
    pointSpreadSource: "NBC Sports, CBSSports.com, NCAA.com",
  },
  {
    id: "match-1-24",
    round: 1,
    roundName: "First Round",
    region: "West",
    date: "Friday, March 21, 2025",
    time: "2:35 PM MST",
    location: "Climate Pledge Arena, Seattle, WA",
    teamA: {
      id: "grand-canyon",
      name: "Grand Canyon",
      seed: 13,
      score: 0,
      record: "24-9",
    },
    teamB: {
      id: "maryland",
      name: "Maryland",
      seed: 4,
      score: 0,
      record: "25-10",
    },
    winner: null,
    predictions: {
      claude: "maryland",
      gpt4o: "maryland",
      perplexity: "maryland",
      deepseek: "maryland",
      grok: "maryland",
      gemini: "maryland",
    },
    teams: [
      {
        id: "grand-canyon",
        name: "Grand Canyon",
        seed: 13,
        score: 0,
        record: "24-9",
      },
      {
        id: "maryland",
        name: "Maryland",
        seed: 4,
        score: 0,
        record: "25-10",
      },
    ],
    pointSpread: 5,
    pointSpreadSource: "Wikipedia, CBSSports.com, NCAA.com",
  },
  {
    id: "match-1-25",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Friday, March 21, 2025",
    time: "4:50 PM MST",
    location: "Lenovo Center, Raleigh, NC",
    teamA: {
      id: "norfolk-state",
      name: "Norfolk State",
      seed: 16,
      score: 0,
      record: "22-11",
    },
    teamB: {
      id: "florida",
      name: "Florida",
      seed: 1,
      score: 0,
      record: "28-6",
    },
    winner: null,
    predictions: {
      claude: "florida",
      gpt4o: "florida",
      perplexity: "florida",
      deepseek: "florida",
      grok: "florida",
      gemini: "florida",
    },
    teams: [
      {
        id: "norfolk-state",
        name: "Norfolk State",
        seed: 16,
        score: 0,
        record: "22-11",
      },
      {
        id: "florida",
        name: "Florida",
        seed: 1,
        score: 0,
        record: "28-6",
      },
    ],
    pointSpread: 3,
    pointSpreadSource: "NCAA.com, CBSSports.com",
  },
  {
    id: "match-1-26",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Friday, March 21, 2025",
    time: "5:10 PM MST",
    location: "Rocket Arena, Cleveland, OH",
    teamA: {
      id: "troy",
      name: "Troy",
      seed: 14,
      score: 0,
      record: "23-11",
    },
    teamB: {
      id: "kentucky",
      name: "Kentucky",
      seed: 3,
      score: 0,
      record: "26-8",
    },
    winner: null,
    predictions: {
      claude: "kentucky",
      gpt4o: "kentucky",
      perplexity: "kentucky",
      deepseek: "kentucky",
      grok: "kentucky",
      gemini: "kentucky",
    },
    teams: [
      {
        id: "troy",
        name: "Troy",
        seed: 14,
        score: 0,
        record: "23-11",
      },
      {
        id: "kentucky",
        name: "Kentucky",
        seed: 3,
        score: 0,
        record: "26-8",
      },
    ],
    pointSpread: 3,
    pointSpreadSource: "NCAA.com, CBSSports.com",
  },
  {
    id: "match-1-27",
    round: 1,
    roundName: "First Round",
    region: "West",
    date: "Friday, March 21, 2025",
    time: "5:25 PM MST",
    location: "Climate Pledge Arena, Seattle, WA",
    teamA: {
      id: "new-mexico",
      name: "New Mexico",
      seed: 10,
      score: 0,
      record: "23-10",
    },
    teamB: {
      id: "marquette",
      name: "Marquette",
      seed: 7,
      score: 0,
      record: "25-9",
    },
    winner: null,
    predictions: {
      claude: "marquette",
      gpt4o: "marquette",
      perplexity: "marquette",
      deepseek: "new-mexico",
      grok: "marquette",
      gemini: "marquette",
    },
    teams: [
      {
        id: "new-mexico",
        name: "New Mexico",
        seed: 10,
        score: 0,
        record: "23-10",
      },
      {
        id: "marquette",
        name: "Marquette",
        seed: 7,
        score: 0,
        record: "25-9",
      },
    ],
    pointSpread: 2,
    pointSpreadSource: "NCAA.com, CBSSports.com",
  },
  {
    id: "match-1-28",
    round: 1,
    roundName: "First Round",
    region: "West",
    date: "Friday, March 21, 2025",
    time: "5:35 PM MST",
    location: "Fiserv Forum, Milwaukee, WI",
    teamA: {
      id: "akron",
      name: "Akron",
      seed: 13,
      score: 0,
      record: "24-10",
    },
    teamB: {
      id: "arizona",
      name: "Arizona",
      seed: 4,
      score: 0,
      record: "26-8",
    },
    winner: null,
    predictions: {
      claude: "arizona",
      gpt4o: "arizona",
      perplexity: "arizona",
      deepseek: "arizona",
      grok: "arizona",
      gemini: "arizona",
    },
    teams: [
      {
        id: "akron",
        name: "Akron",
        seed: 13,
        score: 0,
        record: "24-10",
      },
      {
        id: "arizona",
        name: "Arizona",
        seed: 4,
        score: 0,
        record: "26-8",
      },
    ],
  },
  {
    id: "match-1-29",
    round: 1,
    roundName: "First Round",
    region: "South",
    date: "Friday, March 21, 2025",
    time: "7:25 PM MST",
    location: "Lenovo Center, Raleigh, NC",
    teamA: {
      id: "oklahoma",
      name: "Oklahoma",
      seed: 9,
      score: 0,
      record: "22-12",
    },
    teamB: {
      id: "uconn",
      name: "UConn",
      seed: 8,
      score: 0,
      record: "25-11",
    },
    winner: null,
    predictions: {
      claude: "oklahoma",
      gpt4o: "uconn",
      perplexity: "uconn",
      deepseek: "oklahoma",
      grok: "oklahoma",
      gemini: "uconn",
    },
    teams: [
      {
        id: "oklahoma",
        name: "Oklahoma",
        seed: 9,
        score: 0,
        record: "22-12",
      },
      {
        id: "uconn",
        name: "UConn",
        seed: 8,
        score: 0,
        record: "25-11",
      },
    ],
  },
  {
    id: "match-1-30",
    round: 1,
    roundName: "First Round",
    region: "East",
    date: "Friday, March 21, 2025",
    time: "7:45 PM MST",
    location: "Rocket Arena, Cleveland, OH",
    teamA: {
      id: "xavier-texas",
      name: "Xavier/Texas",
      seed: 11,
      score: 0,
      record: "20-14",
    },
    teamB: {
      id: "illinois",
      name: "Illinois",
      seed: 6,
      score: 0,
      record: "26-8",
    },
    winner: null,
    predictions: {
      claude: "illinois",
      gpt4o: "illinois",
      perplexity: "illinois",
      deepseek: "illinois",
      grok: "xavier-texas",
      gemini: "illinois",
    },
    teams: [
      {
        id: "xavier-texas",
        name: "Xavier/Texas",
        seed: 11,
        score: 0,
        record: "20-14",
      },
      {
        id: "illinois",
        name: "Illinois",
        seed: 6,
        score: 0,
        record: "26-8",
      },
    ],
    pointSpread: 3,
    pointSpreadSource: "NCAA.com, CBSSports.com",
  },
  {
    id: "match-1-31",
    round: 1,
    roundName: "First Round",
    region: "West",
    date: "Friday, March 21, 2025",
    time: "8:00 PM MST",
    location: "Climate Pledge Arena, Seattle, WA",
    teamA: {
      id: "bryant",
      name: "Bryant",
      seed: 15,
      score: 0,
      record: "23-10",
    },
    teamB: {
      id: "michigan-state",
      name: "Michigan State",
      seed: 2,
      score: 0,
      record: "28-7",
    },
    winner: null,
    predictions: {
      claude: "michigan-state",
      gpt4o: "michigan-state",
      perplexity: "michigan-state",
      deepseek: "michigan-state",
      grok: "michigan-state",
      gemini: "michigan-state",
    },
    teams: [
      {
        id: "bryant",
        name: "Bryant",
        seed: 15,
        score: 0,
        record: "23-10",
      },
      {
        id: "michigan-state",
        name: "Michigan State",
        seed: 2,
        score: 0,
        record: "28-7",
      },
    ],
  },
  {
    id: "match-1-32",
    round: 1,
    roundName: "First Round",
    region: "West",
    date: "Friday, March 21, 2025",
    time: "8:10 PM MST",
    location: "Fiserv Forum, Milwaukee, WI",
    teamA: {
      id: "liberty",
      name: "Liberty",
      seed: 12,
      score: 0,
      record: "20-14",
    },
    teamB: {
      id: "oregon",
      name: "Oregon",
      seed: 5,
      score: 0,
      record: "25-9",
    },
    winner: null,
    predictions: {
      claude: "oregon",
      gpt4o: "oregon",
      perplexity: "oregon",
      deepseek: "liberty",
      grok: "liberty",
      gemini: "liberty",
    },
    teams: [
      {
        id: "liberty",
        name: "Liberty",
        seed: 12,
        score: 0,
        record: "20-14",
      },
      {
        id: "oregon",
        name: "Oregon",
        seed: 5,
        score: 0,
        record: "25-9",
      },
    ],
    pointSpread: 2,
    pointSpreadSource: "NCAA.com",
  },
]

// Agent data with full bracket predictions
const agentData = {
  claude: {
    name: "Claude 3.7",
    avatar: "/placeholder.svg?height=40&width=40",
    champion: "Duke",
    finalFour: ["Houston", "Auburn", "Duke", "Florida"],
  },
  gpt4o: {
    name: "GPT-4o",
    avatar: "/placeholder.svg?height=40&width=40",
    champion: "Houston",
    finalFour: ["Auburn", "Duke", "Florida", "Houston"],
  },
  perplexity: {
    name: "Perplexity Sonar",
    avatar: "/placeholder.svg?height=40&width=40",
    champion: "Kansas",
    finalFour: ["Creighton", "Kansas", "Michigan State", "UConn"],
  },
  deepseek: {
    name: "DeepSeek R1",
    avatar: "/placeholder.svg?height=40&width=40",
    champion: "Kansas",
    finalFour: ["Duke", "Houston", "Auburn", "Kansas"],
  },
  grok: {
    name: "Grok 3",
    avatar: "/placeholder.svg?height=40&width=40",
    champion: "Duke",
    finalFour: ["Duke", "Auburn", "Florida", "Houston"],
  },
  gemini: {
    name: "Gemini 2.0",
    avatar: "/placeholder.svg?height=40&width=40",
    champion: "Duke",
    finalFour: ["Duke", "Auburn", "Florida", "Houston"],
  },
}

// Mock API functions for fetching data
export async function fetchBracketData(round: number, agentIds: string[] = []): Promise<Match[]> {
  // Simulate API call delay
  await new Promise((resolve) => setTimeout(resolve, 300))

  // Filter matches by round
  const matchesByRound = tournamentData.filter((match) => match.round === round)

  // If specific agents are selected (not "all"), filter predictions to only include those agents
  if (agentIds.length > 0 && !agentIds.includes("all")) {
    return matchesByRound.map((match) => {
      const filteredPredictions: Record<string, string> = {}

      agentIds.forEach((agentId) => {
        if (match.predictions[agentId]) {
          filteredPredictions[agentId] = match.predictions[agentId]
        }
      })

      return {
        ...match,
        predictions: filteredPredictions,
      }
    })
  }

  return matchesByRound
}

export async function fetchScores(): Promise<Record<string, number>> {
  // Simulate API call delay
  await new Promise((resolve) => setTimeout(resolve, 200))

  // Calculate scores based on correct predictions
  const scores: Record<string, number> = {
    claude: 0,
    gpt4o: 0,
    perplexity: 0,
    deepseek: 0,
    grok: 0,
    gemini: 0,
  }

  // For now, we'll use placeholder scores since we don't have actual results yet
  scores.claude = 320
  scores.gpt4o = 290
  scores.perplexity = 280
  scores.deepseek = 300
  scores.grok = 310
  scores.gemini = 310

  return scores
}

export async function fetchAgents(): Promise<Agent[]> {
  // Simulate API call delay
  await new Promise((resolve) => setTimeout(resolve, 200))

  // Convert agent data to Agent type
  return Object.entries(agentData).map(([id, data]) => ({
    id,
    name: data.name,
    avatar: data.avatar,
    score: 0, // Will be populated from fetchScores
    correctPicks: 0, // Will be calculated based on actual results
  }))
}

